name: Deploy to EC2

on:
  push:
    branches: [main]    # or your deploy branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Sync pos-frontend files
      run: |
        rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./pos-frontend/ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:${{ secrets.FRONTEND_DIR }}

    - name: Sync pos-backend files
      run: |
        rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./pos-backend/ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:${{ secrets.BACKEND_DIR }}

    - name: Install dependencies and restart services
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd ${{ secrets.FRONTEND_DIR }}
          npm install
          pm2 stop pos-frontend || true
          pm2 start npm --name "pos-frontend" -- run dev -- --host

          cd ${{ secrets.BACKEND_DIR }}
          npm install
          pm2 stop pos-backend || true
          pm2 start npm --name "pos-backend" -- run start

          pm2 save
        EOF


