name: Deploy Frontend to EC2

on:
  push:
    branches:
      - main  # or your branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY_B64 }}" | base64 -d > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 13.203.203.151 >> ~/.ssh/known_hosts

    - name: Deploy to EC2 via SSH
      run: |
        ssh ubuntu@13.203.203.151 << 'EOF'
          set -e
          mkdir -p ~/apps
          cd ~/apps

          if [ ! -d "pos-frontend" ]; then
            git clone https://github.com/irfanicc/pos-frontend.git
          else
            cd pos-frontend && git pull origin main && cd ..
          fi

          cd pos-frontend
          docker stop pos-frontend || true
          docker rm pos-frontend || true
          docker build -t pos-frontend .
          docker run -d -p 5173:5173 --name pos-frontend pos-frontend
        EOF

