name: Deploy Frontend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 13.127.217.202 >> ~/.ssh/known_hosts

    - name: Deploy via SSH
      run: |
        ssh ubuntu@13.127.217.202 << 'EOF'
          docker stop pos-frontend || true
          docker rm pos-frontend || true
          cd ~/apps || mkdir -p ~/apps && cd ~/apps
          rm -rf pos-frontend
          git clone https://github.com/<your-username>/pos-frontend.git
          cd pos-frontend
          docker build -t pos-frontend .
          docker run -d -p 5173:5173 --name pos-frontend pos-frontend
        EOF

