name: Deploy React to EC2

on:
  push:
    branches:
      - test

jobs:
  deploy:
    # Explicitly target your self-hosted runner
    runs-on: self-hosted
    
    # You can add labels to be more specific if you have multiple runners
    # runs-on: [self-hosted, linux, x64]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Since we're running on the self-hosted runner, we might not need SSH
      # unless we're deploying to a different instance than the runner
      - name: Verify runner location
        run: |
          echo "Running on $(hostname)"
          echo "IP: $(hostname -I)"
          
      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Docker operations
        run: |
          # Stop and remove existing container if it exists
          docker stop react-app || true
          docker rm react-app || true
          
          # Build new image
          docker build -t react-app .
          
          # Run new container
          docker run -d \
            --name react-app \
            -p 5173:5173 \
            -e VITE_API_URL=https://your-backend-url \
            --restart unless-stopped \
            react-app
